const state={all:[],shown:12,category:"Semua",slide:0,q:"",cart:JSON.parse(localStorage.getItem("tanieCart")||"[]"),fav:JSON.parse(localStorage.getItem("tanieFav")||"[]")};
const rp=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const grid=document.querySelector("#menuGrid"), filters=document.querySelector("#filters");
fetch("data/menu.json").then(r=>r.json()).then(d=>{state.all=d; renderFilters(); renderSignature(); render()});
function filtered(){let a=state.all.filter(x=>(state.category==="Semua"||x.category===state.category)&&x.name.toLowerCase().includes(state.q)); let s=sort.value;if(s==="low")a.sort((a,b)=>a.price-b.price);if(s==="high")a.sort((a,b)=>b.price-a.price);if(s==="rating")a.sort((a,b)=>b.rating-a.rating);return a}
function renderFilters(){let cats=["Semua",...new Set(state.all.map(x=>x.category))];filters.innerHTML=cats.map(c=>`<button class="${c===state.category?"active":""}" data-c="${c}">${c}</button>`).join("");filters.onclick=e=>{if(e.target.dataset.c){state.category=e.target.dataset.c;state.shown=12;state.slide=0;renderFilters();render()}}}
function card(x){let fav=state.fav.includes(x.id);return `<article class="card"><button class="fav" data-fav="${x.id}">${fav?"♥":"♡"}</button><img loading="lazy" src="${x.image}" alt="${x.name}"><div class="card-body"><div class="meta"><span>${x.category}</span><span>★ ${x.rating}</span></div><h3>${x.name}</h3><p>${x.description}</p><div class="bottom"><span class="price">${rp(x.price)}</span><button class="add" data-add="${x.id}">+</button></div></div></article>`}
function render(){let a=filtered();let perPage=12;let pages=Math.max(1,Math.ceil(a.length/perPage));state.slide=Math.min(state.slide,pages-1);let start=state.slide*perPage;resultCount.textContent=`${a.length} menu ditemukan`;grid.innerHTML=a.slice(start,start+perPage).map(card).join("");loadMore.style.display="none";slideInfo.textContent=`Slide ${state.slide+1} / ${pages}`;prevSlide.disabled=state.slide===0;nextSlide.disabled=state.slide>=pages-1;bindCards()}
function bindCards(){document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=()=>{let id=+b.dataset.fav;state.fav=state.fav.includes(id)?state.fav.filter(x=>x!==id):[...state.fav,id];localStorage.setItem("tanieFav",JSON.stringify(state.fav));render()})}
function renderSignature(){let picks=["Kopi Senja","Cloud Coffee","Biscoff Dream","Midnight Mocha"].map(n=>state.all.find(x=>x.name===n)).filter(Boolean);signatureGrid.innerHTML=picks.map(x=>`<div class="sig-card"><img loading="lazy" src="${x.image}" alt="${x.name}"><div><b>${x.name}</b><small>${rp(x.price)}</small></div></div>`).join("")}
search.oninput=e=>{state.q=e.target.value.toLowerCase();state.shown=12;state.slide=0;render()};sort.onchange=()=>{state.slide=0;render()};loadMore.onclick=()=>{};prevSlide.onclick=()=>{if(state.slide>0){state.slide--;render();document.querySelector("#menuGrid").scrollIntoView({behavior:"smooth",block:"start"})}};nextSlide.onclick=()=>{let pages=Math.ceil(filtered().length/12);if(state.slide<pages-1){state.slide++;render();document.querySelector("#menuGrid").scrollIntoView({behavior:"smooth",block:"start"})}};
function add(id){let x=state.all.find(x=>x.id===id), old=state.cart.find(x=>x.id===id);old?old.qty++:state.cart.push({...x,qty:1});saveCart();toast(x.name+" ditambahkan ke keranjang ☕")}
function saveCart(){localStorage.setItem("tanieCart",JSON.stringify(state.cart));cartCount.textContent=state.cart.reduce((s,x)=>s+x.qty,0);renderCart()}
function renderCart(){cartItems.innerHTML=state.cart.length?state.cart.map(x=>`<div class="cart-item"><img src="${x.image}"><div><b>${x.name}</b><small>${rp(x.price)} × ${x.qty}</small></div><button data-remove="${x.id}">−</button></div>`).join(""):"<p>Keranjangmu masih kosong ☕</p>";total.textContent=rp(state.cart.reduce((s,x)=>s+x.price*x.qty,0));document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{let x=state.cart.find(x=>x.id===+b.dataset.remove);if(--x.qty===0)state.cart=state.cart.filter(y=>y.id!==x.id);saveCart()})}
cartBtn.onclick=()=>cart.classList.add("open");closeCart.onclick=()=>cart.classList.remove("open");checkout.onclick=()=>toast(state.cart.length?"Pesanan siap diproses! Terima kasih ♡":"Keranjang masih kosong");
randomBtn.onclick=()=>{let x=state.all[Math.floor(Math.random()*state.all.length)];state.q=x.name.toLowerCase();state.category="Semua";state.shown=12;state.slide=0;renderFilters();render();document.querySelector("#menu").scrollIntoView({behavior:"smooth"});toast("Coba "+x.name+" hari ini ✨")};
function toast(t){toastEl=document.querySelector("#toast");toastEl.textContent=t;toastEl.classList.add("show");setTimeout(()=>toastEl.classList.remove("show"),2400)}saveCart();